### ISSUE TITLE
readme.md: tutorial folders hint is old information

### ISSUE THREAD

**Issue by ThomasFinnern** [astridx/boilerplate#5]
In the general readme it states the following

> Tutorial Sample Files
You can find the Tutorial Sample Files in the folder Tutorial :)

You may have to update the readme or create the tutorial folder again or i miss something.
The "word" tutorial could be a link to the file.
 
I like to compare the changes between the "stages"/versions by my merge tool. Therefore i would like to get all examples in one base folder 

The versions exist in several repositories so it is against the dry principle to keep it on a second place as double content.  So i will be not disapointed if you ignore my wishes.

**Comment by astridx** [comment]
Thank you for your advice. Sorry for my late reply.

You're right. In the [Read.m](https://github.com/astridx/boilerplate/blob/tutorial/README.md)e I wrote that the sample files are in a directory called tutorial. This is not the case at the moment. I have corrected the text. But: I would like to set it up again. That's why I leave this issue open. At the moment, however, something is constantly changing and it is easier to keep changes in the branches in sync than to copy them from one directory to another.

Did you see that you can see the changes here on Github? For example the url
https://github.com/astridx/boilerplate/compare/t8...t9
shows you the changes form branch t8 to t9 - form chapter 8 to chapter 9.

**Comment by astridx** [comment]
I added a version of every branch here: https://github.com/astridx/boilerplate/tree/tutorial/tutorial/2021_03_27
